//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSettings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S:\Exchange\-\Samples\Easypay\in\</string>
  <string>S:\Exchange\-\Samples\Easypay\out\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection pathGetEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pathGetEasypay"]));
            }
            set {
                this["pathGetEasypay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S:\Exchange\-\Samples\Delay\in\</string>
  <string>S:\Exchange\-\Samples\Delay\out\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection pathGetDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pathGetDelay"]));
            }
            set {
                this["pathGetDelay"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S:\Exchange\-\Samples\Easypay\in\</string>
  <string>S:\Exchange\-\Samples\Easypay\out\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultPathGetEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultPathGetEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S:\Exchange\-\Samples\Delay\in\</string>
  <string>S:\Exchange\-\Samples\Delay\out\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultPathGetDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultPathGetDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>L:\\Cards\\DB2\\001\\</string>\r\n  <string>L:\\Cards\\DB4\\001\\</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection defaultPathCopyEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultPathCopyEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>M:\\KREDIT\\DB2\\001\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultPathCopyDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultPathCopyDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>xls</string>
  <string>xlsb</string>
  <string>xlsm</string>
  <string>xlsx</string>
  <string>DBF</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S6</string>
  <string>S61</string>
  <string>C2</string>
  <string>C6</string>
  <string>D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection dBasesEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["dBasesEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S6</string>
  <string>S61</string>
  <string>S88</string>
  <string>D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection dBasesDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["dBasesDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S6</string>
  <string>S61</string>
  <string>S88</string>
  <string>D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultDBasesDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultDBasesDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>S6</string>
  <string>S61</string>
  <string>C2</string>
  <string>C6</string>
  <string>D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultDBasesEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultDBasesEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>База</string>
  <string>Номер кошелька</string>
  <string>Дата открытия</string>
  <string>Остаток</string>
  <string>Овердрафт</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultColumnsEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultColumnsEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>База</string>
  <string>Наименование продукта</string>
  <string>Номер счета</string>
  <string>Валюта</string>
  <string>Овердрафт</string>
  <string>Номер кошелька</string>
  <string>Статус кошелька</string>
  <string>Дата открытия</string>
  <string>Остаток</string>
  <string>Дата последнего зачисления</string>
  <string>Дата последней операции</string>
  <string>Наименование организации, перечисляющей денежные средства</string>
  <string>Арест</string>
  <string>Детали ареста</string>
  <string>Обременитель</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultColumnsDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultColumnsDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>Овердравт</string>
  <string>Номер кошелька</string>
  <string>Дата открытия счета</string>
  <string>Остаток</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultFinalColumnsEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultFinalColumnsEasypay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>Валюта</string>
  <string>Овердравт</string>
  <string>Остаток</string>
  <string>Дата последнего зачисления</string>
  <string>Арест</string>
  <string>Дата открытия счета</string>
  <string>Дата закрытия счета</string>
  <string>Дата последней операции</string>
  <string>IBAN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection defaultFinalColumnsDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["defaultFinalColumnsDelay"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>L:\\Cards\\DB2\\001\\</string>\r\n  <string>L:\\Cards\\DB4\\001\\</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection pathCopyEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pathCopyEasypay"]));
            }
            set {
                this["pathCopyEasypay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>M:\\KREDIT\\DB2\\001\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection pathCopyDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pathCopyDelay"]));
            }
            set {
                this["pathCopyDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>База</string>
  <string>Номер кошелька</string>
  <string>Дата открытия</string>
  <string>Остаток</string>
  <string>Овердрафт</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection columnsEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["columnsEasypay"]));
            }
            set {
                this["columnsEasypay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>База</string>
  <string>Наименование продукта</string>
  <string>Номер счета</string>
  <string>Валюта</string>
  <string>Овердрафт</string>
  <string>Номер кошелька</string>
  <string>Статус кошелька</string>
  <string>Дата открытия</string>
  <string>Остаток</string>
  <string>Дата последнего зачисления</string>
  <string>Дата последней операции</string>
  <string>Наименование организации, перечисляющей денежные средства</string>
  <string>Арест</string>
  <string>Детали ареста</string>
  <string>Обременитель</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection columnsDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["columnsDelay"]));
            }
            set {
                this["columnsDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>Овердравт</string>
  <string>Номер кошелька</string>
  <string>Дата открытия счета</string>
  <string>Остаток</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection finalColumnsEasypay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["finalColumnsEasypay"]));
            }
            set {
                this["finalColumnsEasypay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ID</string>
  <string>Орган</string>
  <string>Вх № запроса</string>
  <string>Исполнитель</string>
  <string>Фамилия</string>
  <string>Имя</string>
  <string>Отчество</string>
  <string>Идентификационный номер</string>
  <string>Дата рождения</string>
  <string>Серия, номер паспорта</string>
  <string>Валюта</string>
  <string>Овердравт</string>
  <string>Остаток</string>
  <string>Дата последнего зачисления</string>
  <string>Арест</string>
  <string>Дата открытия счета</string>
  <string>Дата закрытия счета</string>
  <string>Дата последней операции</string>
  <string>IBAN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection finalColumnsDelay {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["finalColumnsDelay"]));
            }
            set {
                this["finalColumnsDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>xls</string>
  <string>xlsb</string>
  <string>xlsm</string>
  <string>xlsx</string>
  <string>DBF</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["extensions"]));
            }
            set {
                this["extensions"] = value;
            }
        }
    }
}
